# Compilación
main:
	@echo "Compilando ficheros..."
	g++-13 -o netcp -std=c++23 main_netcp.cpp netcp.cpp

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f netcp